name: Deploy statico su GitHub Pages

# Controlla quando eseguire il workflow
on:
  # Si attiva quando viene fatto un push sul branch main
  push:
    branches: [ "main" ]
  
  # Permette di eseguire questo workflow manualmente dalla tab Actions
  workflow_dispatch:

# Imposta i permessi GITHUB_TOKEN necessari per il deploy su GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Consente una sola implementazione del deploy alla volta
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job per la verifica e ottimizzazione
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Installa dipendenze
        run: |
          npm install -g html-minifier terser clean-css-cli eslint
      
      - name: Lint JavaScript
        run: |
          eslint js/script.js --no-eslintrc --parser-options=ecmaVersion:2022 --env browser --rule 'no-undef: "error"' --rule 'no-unused-vars: "warn"' --fix || echo "Linting completato con avvisi"
      
      - name: Ottimizza CSS
        run: |
          mkdir -p dist/css
          cleancss -o dist/css/style.min.css css/style.css
      
      - name: Ottimizza JavaScript
        run: |
          mkdir -p dist/js
          terser js/script.js -o dist/js/script.min.js
      
      - name: Minifica HTML
        run: |
          mkdir -p dist
          html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true --input-dir ./ --output-dir dist/ --file-ext html
          

      - name: Aggiorna riferimenti ai file minificati
        run: |
          sed -i 's/css\/style.css/css\/style.min.css/g' dist/index.html
          sed -i 's/js\/script.js/js\/script.min.js/g' dist/index.html
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: './dist'

  # Job per il deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
